# Задание 2.

**NB. Все упражнения ниже нужно делать без использования циклов Python в явном (`while`, `for`) и неявном виде (list comprehension, `map`, `reduce` и пр)**

Задания по манипуляциям с массивами чаще всего решаются в одно/два выражения. 

In [3]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

A = np.random.randint(0, 100, size=(20, 5))
A

array([[33, 99, 68, 12, 52],
       [42, 38, 60, 45, 15],
       [67, 73, 47, 98, 29],
       [16, 17, 17, 74, 92],
       [49, 12, 87, 15, 42],
       [84, 76, 15, 96,  3],
       [48, 52, 62, 14, 22],
       [25, 46, 55,  1,  3],
       [16, 72, 78, 50, 69],
       [63, 46, 10,  4, 52],
       [17, 80,  1, 72, 62],
       [82, 50,  7, 70, 31],
       [69, 46, 52, 76, 36],
       [46, 90, 20, 35, 95],
       [ 4, 75, 55, 63, 30],
       [46, 98, 42, 56, 84],
       [36, 66, 72, 22, 66],
       [37, 32, 63, 44,  4],
       [13, 32, 70, 89, 96],
       [67,  8, 13, 18, 82]])

# Задание 2.1 (2 балла)

Сгенерируйте новый массив, в котором столбцы массива `A` переставлены в случайном порядке

Для случайной перестановки столбцов массива можно использовать две команды:
- np.random.permutation(array) - сохраняет исходный массив, возвращает изменённый новый массив
- np.random.shuffle(array) - изменяет сам входной массив.

Для многомерного массива происходит перестановка по первой оси, то есть для двумерного массива будут перемешаны строки, значин предварительно нужно транспонировать массив. 

Рассмотрим сначала на более наглядном примере:

In [4]:
test_array = np.random.randint(0, 100, size=(5, 5))
test_array

array([[ 4, 68,  3, 81, 75],
       [96, 91, 11, 95, 64],
       [66, 20, 84, 42, 34],
       [19, 29, 93, 69, 59],
       [ 0, 98, 85, 42, 77]])

In [5]:
np.random.permutation(test_array.transpose()).transpose()

array([[ 4, 75, 68,  3, 81],
       [96, 64, 91, 11, 95],
       [66, 34, 20, 84, 42],
       [19, 59, 29, 93, 69],
       [ 0, 77, 98, 85, 42]])

Тогда применим эту функцию к массиву А и получим случайную перестановку столбцов

In [6]:
np.random.permutation(A.transpose()).transpose()

array([[99, 33, 52, 68, 12],
       [38, 42, 15, 60, 45],
       [73, 67, 29, 47, 98],
       [17, 16, 92, 17, 74],
       [12, 49, 42, 87, 15],
       [76, 84,  3, 15, 96],
       [52, 48, 22, 62, 14],
       [46, 25,  3, 55,  1],
       [72, 16, 69, 78, 50],
       [46, 63, 52, 10,  4],
       [80, 17, 62,  1, 72],
       [50, 82, 31,  7, 70],
       [46, 69, 36, 52, 76],
       [90, 46, 95, 20, 35],
       [75,  4, 30, 55, 63],
       [98, 46, 84, 42, 56],
       [66, 36, 66, 72, 22],
       [32, 37,  4, 63, 44],
       [32, 13, 96, 70, 89],
       [ 8, 67, 82, 13, 18]])

# Задание 2.2 (5 баллов)

Сгенерируйте новый массив, который содержит только те строки массива `A`, в которых: 
- сумма элементов по четным столбцам (индексы $0, 2, \ldots$) больше среднего значения (по всему массиву) суммы элементов по нечетным столбцам (индексы $1, 3, \ldots$) 

Проссумируем элементы по нечетным столбцам и возьмет среднее значение:

In [7]:
mean_odd = np.sum(A[:,1::2], axis=1).mean()
mean_odd

103.1

Создадим маску проверки условия, что сумма элементов по четным столбцам больше среднего значения суммы по нечетным столбцам

In [8]:
mask = np.sum(A[:,0::2], axis=1) > mean_odd
mask

array([ True,  True,  True,  True,  True, False,  True, False,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [9]:
A[mask, :]

array([[33, 99, 68, 12, 52],
       [42, 38, 60, 45, 15],
       [67, 73, 47, 98, 29],
       [16, 17, 17, 74, 92],
       [49, 12, 87, 15, 42],
       [48, 52, 62, 14, 22],
       [16, 72, 78, 50, 69],
       [63, 46, 10,  4, 52],
       [82, 50,  7, 70, 31],
       [69, 46, 52, 76, 36],
       [46, 90, 20, 35, 95],
       [46, 98, 42, 56, 84],
       [36, 66, 72, 22, 66],
       [37, 32, 63, 44,  4],
       [13, 32, 70, 89, 96],
       [67,  8, 13, 18, 82]])

# Задача 2.3 (3 балла)

Найдите индекс строки массива `A`, в которой разница между максимальным и минимальным элементом максимальна

In [10]:
np.argmax(np.max(A, axis=1) - np.min(A, axis=1))

5

# Задание 2.4 (7 баллов)

Сгенерируйте массив той же размерности, что и `A`, но в котором каждый элемент заменен на его порядковый номер (начиная с 1) в отсортированном по возрастанию массиве из элементов `A`

Если `A` выглядит так:
$$
\begin{pmatrix}
12 & 14\\
1 & 2
\end{pmatrix}
$$
то результат должен быть
$$
\begin{pmatrix}
3 & 4\\
1 & 2
\end{pmatrix}
$$

*Tip: рассмотрите возможность неоднократного применения [argsort()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.argsort.html)*

In [11]:
A

array([[33, 99, 68, 12, 52],
       [42, 38, 60, 45, 15],
       [67, 73, 47, 98, 29],
       [16, 17, 17, 74, 92],
       [49, 12, 87, 15, 42],
       [84, 76, 15, 96,  3],
       [48, 52, 62, 14, 22],
       [25, 46, 55,  1,  3],
       [16, 72, 78, 50, 69],
       [63, 46, 10,  4, 52],
       [17, 80,  1, 72, 62],
       [82, 50,  7, 70, 31],
       [69, 46, 52, 76, 36],
       [46, 90, 20, 35, 95],
       [ 4, 75, 55, 63, 30],
       [46, 98, 42, 56, 84],
       [36, 66, 72, 22, 66],
       [37, 32, 63, 44,  4],
       [13, 32, 70, 89, 96],
       [67,  8, 13, 18, 82]])

In [25]:
np.argsort(np.argsort(A, axis=1), axis=1)

array([[1, 4, 3, 0, 2],
       [2, 1, 4, 3, 0],
       [2, 3, 1, 4, 0],
       [0, 1, 2, 3, 4],
       [3, 0, 4, 1, 2],
       [3, 2, 1, 4, 0],
       [2, 3, 4, 0, 1],
       [2, 3, 4, 0, 1],
       [0, 3, 4, 1, 2],
       [4, 2, 1, 0, 3],
       [1, 4, 0, 3, 2],
       [4, 2, 0, 3, 1],
       [3, 1, 2, 4, 0],
       [2, 3, 0, 1, 4],
       [0, 4, 2, 3, 1],
       [1, 4, 0, 2, 3],
       [1, 2, 4, 0, 3],
       [2, 1, 4, 3, 0],
       [0, 1, 2, 3, 4],
       [3, 0, 1, 2, 4]])

In [31]:
np.argsort(np.argsort(A, axis=0), axis=0) + np.argsort(np.argsort(A, axis=1), axis=1)

array([[ 7, 23, 18,  2, 12],
       [11,  6, 16, 12,  3],
       [17, 16,  9, 23,  5],
       [ 2,  3,  7, 18, 21],
       [16,  1, 23,  5, 11],
       [22, 17,  5, 22,  0],
       [14, 13, 17,  3,  5],
       [ 7, 11, 14,  0,  2],
       [ 3, 15, 22, 11, 16],
       [18,  9,  3,  1, 14],
       [ 5, 20,  0, 17, 14],
       [22, 11,  1, 16,  8],
       [20,  7, 11, 20,  8],
       [13, 20,  6,  8, 22],
       [ 0, 18, 13, 15,  7],
       [11, 22,  7, 13, 19],
       [ 8, 13, 21,  6, 16],
       [10,  4, 18, 11,  2],
       [ 1,  5, 18, 20, 23],
       [19,  0,  4,  7, 19]])

In [35]:
np.unique(A).shape

(61,)

# Задание 2.5 (2 балла)

Примените $\min-\max$ - нормализацию к строкам массива `A`. То есть нужно получить новый массивы, в каждой строке которого максимальный элементы равен $1$, минимальный - $0$. 

In [355]:
rows_count = A.shape[0]
min_args = A.min(axis=1).reshape(rows_count, 1)
max_args = A.max(axis=1).reshape(rows_count, 1)

In [356]:
(A - min_args) / (max_args - min_args)

array([[0.59615385, 0.07692308, 1.        , 0.98076923, 0.        ],
       [1.        , 0.7012987 , 0.80519481, 0.33766234, 0.        ],
       [0.03030303, 1.        , 0.        , 0.96969697, 0.39393939],
       [1.        , 0.02702703, 0.24324324, 0.        , 0.48648649],
       [0.77966102, 1.        , 0.77966102, 0.        , 0.50847458],
       [1.        , 0.08510638, 0.9787234 , 0.        , 0.07446809],
       [1.        , 0.76041667, 0.75      , 0.        , 0.78125   ],
       [0.39361702, 0.        , 0.9787234 , 0.39361702, 1.        ],
       [0.23214286, 0.89285714, 1.        , 0.60714286, 0.        ],
       [1.        , 0.5       , 0.36842105, 0.        , 0.59210526],
       [0.42857143, 0.65714286, 0.        , 1.        , 0.27142857],
       [0.61842105, 0.40789474, 0.43421053, 0.        , 1.        ],
       [0.        , 1.        , 0.95652174, 0.62318841, 0.49275362],
       [0.46153846, 0.        , 0.86538462, 1.        , 0.30769231],
       [0.        , 0.59340659, 0.